### ISSUE TITLE
api: search claims

### ISSUE THREAD

**Issue by jbenito3** [inveniosoftware/claimstore#23]
Add some kind of search capabilities so claims can be fetched by specifying some filters as described in the [RFC](https://github.com/inveniosoftware/claimstore/blob/master/docs/index.rst).

**Comment by tiborsimko** [comment]
For the time being, additional URL arguments can be simply Boolean AND query additions.  

Later, we could expose complete JSONB like syntax for connaisseurs, depending on evolving needs.
