### ISSUE TITLE
claims: author identity

### ISSUE THREAD

**Issue by zimeon** [inveniosoftware/claimstore#28]
It would be good to be able to exchange information about author identity, certainly ORCID iDs but perhaps others too. I can see wanting to be able to do this with or without publication id correspondence information so probably it should be a separate claim or claims. Not sure whether a claim for each author or a set of claims for a paper would be best.

**Comment by tiborsimko** [comment]
In the RFC, I used `J.R.Ellis.1` persistent identifier type example, thinking about "INSPIRE author ID <-> ORCID"  types of claims, using the usual `is_same_as` predicate:

```json
    {
      "claimant": "INSPIRE",
      "subject": {
          "type": "INSPIRE_AUTHOR_ID",
          "value": "J.R.Ellis.1"
       },
      "claim": {
          "predicate": "is_same_as",
          "datetime": "2015-05-26 11:00:00 UTC",
          "certainty": 1,
      },
      "object": {
           "type": "ORCID_ID",
           "value": "0000-0001-5882-6823"
      }
    }
```

For "author <-> paper" kind of relations, we could introduce a new `is_author_of` predicate:

```json
    {
      "claimant": "INSPIRE",
      "subject": {
          "type": "INSPIRE_AUTHOR_ID",
          "value": "J.R.Ellis.1"
       },
      "claim": {
          "predicate": "is_author_of",
          "datetime": "2015-05-26 11:00:00 UTC",
          "certainty": 1,
      },
      "object": {
           "type": "ADS_BIBCODE",
           "value": "2005astro.ph..1001H"
      }
    }
```

(modulo full URIs and ISO Z dates discussed elsewhere)

**Comment by tiborsimko** [comment]
Based on live discussions, it seemed the overall agreement was to issue a set of claims of the type: "this and this person (=ORCID) `is_author_of` that and that paper (=DOI)" without paying any particular attention to the position of the author in the authorship list of the paper.  Hence a simple set of claims for each author will be sufficient.
