### ISSUE TITLE
tests: isort vs flake8 import order differences

### ISSUE THREAD

**Issue by jbenito3** [inveniosoftware/claimstore#33]
The current situation with flake8 and py.test, regarding PEP8 import order, is not perfect. Many times they give contradictory results. As a consequence we are filling the code with `noqa` and `isort:skip` comments.

**Comment by tiborsimko** [comment]
Note that this issue is bigger than ClaimStore, touching other Invenio ecosystem components as well. Ideally, we'll reconcile the two tools (flake8 and isort) inside `kwalitee` (that for now uses flake8), so the solution can come from there.   

Anyway, ClaimStore uses only `isort` officially...

**Comment by tiborsimko** [comment]
BTW within inveniosoftware we have decided to move to more closely to `pytest` and `isort`, hence let's remove `flake8-import-order` based checks and rely on `flake8-isort` locally.
