### ISSUE TITLE
claims: full URI for subjects/objects

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/claimstore#4]
As discussed via email, it may be interesting to use full URIs for subjects and objects in individual claims, for example:

```json
  {
       "claimant": "ADS",
       "subject": "http://arxiv.org/art/astro-ph/0501001",
       "predicate": "is_same_as",
       "datetime": "2015-05-26 11:00:00 UTC",
       "certainty": 0.9,
       "arguments": {
          "human": 0,
          "actor": "ADS_record_generator"
       },
       "object": "http://ads.../2005astro.ph..1001H"
     }
  }
```

Pros: such data has very direct exposure to the LD world without a need to resolve references.  Cons: prone to service DNS changes or URL structures.

**Comment by kaplun** [comment]
Indeed, in a not too distant future we are going to change `inspirehep.net` to `www.inspirehep.net`. What do you foreseen then?

**Comment by tiborsimko** [comment]
@kaplun Yes, this is why the original RFC was using separated type/value like:

```
"subject": {
          "type": "ARXIV_ID",
          "value": "astro-ph/0501001"
       },
```

Let's weigh pros and cons and see.

**Comment by tiborsimko** [comment]
FWIW, keeping the above flat structure with separated identifier type/value for now.  In case of moving to the full URI, let's reopen later.

**Comment by tiborsimko** [comment]
(see also #80)
