### ISSUE TITLE
access: finer allowed IP configuration

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/claimstore#77]
Following upon #58, it would be nice if the IP check allowed for wildcard expressions like:

```
CLAIMSTORE_ALLOWED_IPS = ['137.138.*.*']
```

or even better using IP subnet masks:

```
CLAIMSTORE_ALLOWED_IPS = ['192.168.0.0/24']
```

See for example what we did in Invenio v1.2:

- https://github.com/inveniosoftware/invenio/blob/maint-1.2/modules/webaccess/lib/access_control_firerole.py#L318-L337

**Comment by jbenito3** [comment]
@tiborsimko I was thinking of using some lib like: https://docs.python.org/3/library/ipaddress.html
