### ISSUE TITLE
system: finalise the list of useful claim predicate types

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/claimstore#8]
In the [RFC](https://github.com/inveniosoftware/claimstore/blob/master/docs/index.rst#33-claim-types), the possible claim predicate types included:
 
- ``is_same_as``
- ``is_different_than``
- ``is_cited_by``
- ``is_erratum_of``
- ``is_superseded_by``
- ``is_software_for_paper``
- ``is_dataset_for_paper``
- ``is_dataset_for_software``

This stemmed from the basic need of identifying persistent ID equivalence, but also served as an illustration of the claim types that may be wanted later.

We should finalise which types of claims are interesting to start with and find good terminology for them.

**Comment by zimeon** [comment]
Comments in email thread: `is_same_as` might be too strong in most cases, perhaps something like 'is_version_of' to relate preprint/postprint/publisher versions. However, some issues of confusion with other notions of versioning (e.g. arXiv's v1 v2 v3...)

**Comment by lnielsen** [comment]
``is_same_as`` I think is for objects that are exactly the same (e.g. DOI X is same as Bibcode Y). I would use ``is_new_version/is_past_version`` for arXiv v1 v2 v3 versions. For arXiv-preprint relation to published-paper i'm not sure I would use ``is_version_of``, rather something like ``is_variant_form_of`` or ``is_superseded_by``. See DataCite related identifier relationships for inspiration. 

Also, I think there's a mix between relationships and object types. Resource type (software, dataset, preprint, article) is a property of the object, not the relationship.

Last but not least I would start out with as small a list of relationships as possible: ``is_same_as`` and if needed ``is_cited_by`` could do. It's much harder to remove relationships than add them later.

**Comment by zimeon** [comment]
I was not clear in my previous comment about arXiv versions: we simply do not know which version we have, it might be a preprint, a postprint, or an identical copy of a formally published version. Thus we could use `is_version_of` or `is_variant_of` but not `is_superseded_by` (e.g. for a paper of my own, the arXiv version includes a correction for a typo in the printed Elsevier one: <http://arxiv.org/abs/hep-lat/9808006>. So, logically <http://arxiv.org/art/hep-lat/9808006v1> `is_superseded_by` <http://doi.org/10.1016/S0370-2693(98)01216-7> `is_superseded_by` <http://arxiv.org/art/hep-lat/9808006v2> (though we'll never have the data to express that).

I do agree with the sentiment that we should probably start with a small set of relationships. Perhaps `is_same_as` (arXiv would not use this), `is_variant_of`, 'is_cited_by` (and inverse: `cites`?).

**Comment by kaplun** [comment]
Do we actually need the inverse relations? I guess the API will always allow to swap subject and object?

At INSPIRE we might be interested indeed into stating when an arXiv preprint corresponds to a published document (hence `is_variant_of`, I guess). At the same time, typically by hand, we are recording erratum information (and we could receive this also from SCOAP3. Another very important relation is the parent/children one (e.g. among Proceedings and their single contributions). And Book chapters and the corresponding books. 

But again it's true that the first and foremost important relation we would like to exchange is the `is_variant_of` one, in order to help us in the de-duplication effort.

**Comment by tiborsimko** [comment]
> I guess the API will always allow to swap subject and object?

Yes.

**Comment by tiborsimko** [comment]
| Last but not least I would start out with as small a list of relationships as possible

That's exactly the [proposed approach](https://github.com/inveniosoftware/claimstore/blob/master/docs/index.rst#33-claim-types).  The purpose of this RFC is to clarify which other predicates we might be interested to include from the get-go...

**Comment by tiborsimko** [comment]
Brainstorming about useful relations and possible names:

- `is_same_as`: when 100% equivalence, e.g. a local copy of an arXiv
  record, with either the same or enriched metadata, e.g. ORCID
  corresponds to this INSPIRE ID

- `is_variant_of`: lesser claim, e.g. arXiv preprint and DOI of a
  published paper, e.g. when INSPIRE merges two sources into one

- `is_author_of`: this person is the author of this document

- `is_contributor_to`: this person is
  supervisor/translator/spokesperson of this document

- `is_erratum_of`: if INSPIRE record R1 is variant of DOI1, and DOI2
  is erratum of DOI1, but INSPIRE merges all these in the same record,
  then three claims: R1 is variant of DOI1, DOI2 is erratum of DOI1,
  R1 is variant of DOI2

Notes:

- some relations are transitive (`is_same_of`), some are not
  (`is_erratum_of`)

- ClaimStore server can optionally resolve queries related to
  transitive relations, the others are left for clients to resolve

- when a claim is revoked via REST API (=replaced by a new claim),
  then the status column of the old claim is updated; the query API
  returns "active" claims by default, but may have return other
  expired claims on demand

- when a service gets info about DOI from another service, ideally it
  shouldn't push it back automatically; only when claims are generated
  by the service; or at least say in arguments how the claim was got

- scenario: ads1 - arxiv1 - 1.0, later ads1 - doi - 0.5, should second
  claim invalidate the first one and make two claims with any wanted
  certainty? or should ADS claim only arxiv1-doi correspondences?

- how much claims if 5 identifiers present? either all, or only
  selectively wanted ones
